# Site Configuration
theme: default
lang: "en"
plugins: []

# HTML Title
title: "YVNS Athletics | Victory Hub"

# Avatar image path
avatar: "https://github.com/yvns-athletics.png"

# Name section text
name: "YVNS ATHLETICS"

# Main brand motto
tagline: >-
  YOUR VICTORY NEEDS SACRIFICE.

# Main links
links:
  - link:
      icon: "fa-solid fa-bag-shopping"
      text: "SHOP YVNS"
      url: "https://yvnsathletics.com"
      alt: "Shop YVNS Athletics"
      title: "Shop YVNS Athletics"
      target: "_blank"

  - link:
      icon: "fa-solid fa-shirt"
      text: "UNBROKEN COLLECTION"
      url: "https://yvnsathletics.com/collections/unbroken-collection"
      alt: "Unbroken Collection"
      title: "Unbroken Collection"
      target: "_blank"

  - link:
      icon: "fa-solid fa-bullseye"
      text: "OUR MISSION"
      url: "https://yvnsathletics.com/pages/the-mission"
      alt: "YVNS Mission"
      title: "YVNS Mission"
      target: "_blank"

  - link:
      icon: "fa-brands fa-instagram"
      text: "INSTAGRAM"
      url: "https://www.instagram.com/yvnsathletics"
      alt: "YVNS Instagram"
      title: "YVNS Instagram"
      target: "_blank"

  - link:
      icon: "fa-brands fa-tiktok"
      text: "TIKTOK"
      url: "https://www.tiktok.com/@yvnsathletics"
      alt: "YVNS TikTok"
      title: "YVNS TikTok"
      target: "_blank"

# Contact icons
socials:
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:support@yvnsathletics.com"
      title: "Email Support"
      alt: "Email Support"
      target: "_blank"

  - social:
      icon: "fa-solid fa-comment-sms"
      url: "sms:+14842732465"
      title: "Text Us"
      alt: "Text Us"
      target: "_blank"

# Footer text
footer: >
  ANY AGE. ANY STRUGGLE. STILL IN IT.

# Footer copyright message
copyright: >
  © 2026 YVNS Athletics.
